package test

public final class E1 : java.lang.Exception {
    public constructor E1()
    public final /*fake_override*/ val cause: kotlin.Throwable?
    public final /*fake_override*/ val message: kotlin.String?
    public final /*fake_override*/ fun printStackTrace(): kotlin.Unit
}

public final class E2 : java.lang.Exception {
    public constructor E2()
    public final /*fake_override*/ val cause: kotlin.Throwable?
    public final /*fake_override*/ val message: kotlin.String?
    public final /*fake_override*/ fun printStackTrace(): kotlin.Unit
}

public/*package*/ open class JavaClass {
    public/*package*/ constructor JavaClass()
    public/*package*/ open fun testMethod(): kotlin.Unit
}

public final class Test {
    public constructor Test()
    public final fun none(): kotlin.Unit
    public final fun one(): kotlin.Unit
    public final fun two(): kotlin.Unit
}
