package test

fun nothing(): Array<in Number> = throw Exception()
